### ISSUE TITLE
Release sdx-controller 2.0.0

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/sdx-controller#170]
- [ ] Write changelog entries
- [ ] Bump up version 2.0.0 in setup.py
- [ ] Bump up pce and datamodel versions in requirements.txt
- [ ] Add a git tag for the release 
- [ ] Make a GitHub release
